/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/budget': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Spend per provider (key fingerprints only) */
    get: operations['budget_api_budget_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a live or replay run */
    post: operations['start_run_api_runs_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run status and result */
    get: operations['get_run_api_runs__run_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stream run events (SSE) */
    get: operations['events_api_runs__run_id__events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/scenarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List scenarios */
    get: operations['list_scenarios_api_scenarios_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/scenarios/{scenario_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Scenario detail */
    get: operations['scenario_api_scenarios__scenario_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/scenarios/{scenario_id}/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Document text */
    get: operations['documents_api_scenarios__scenario_id__documents_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/scenarios/{scenario_id}/recordings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Recordings available for replay, newest first */
    get: operations['recordings_api_scenarios__scenario_id__recordings_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ApiError
     * @description Machine-readable error code plus a user-presentable message.
     */
    ApiError: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** BudgetReport */
    BudgetReport: {
      /** Ledger Initialised */
      ledger_initialised: boolean;
      /** Providers */
      providers: components['schemas']['BudgetRow'][];
    };
    /** BudgetRow */
    BudgetRow: {
      /** Cap */
      cap: string;
      /** Key Configured */
      key_configured: boolean;
      /** Provider */
      provider: string;
      /** Remaining */
      remaining: string | null;
      /** Reserved */
      reserved: string | null;
      /** Spent */
      spent: string | null;
    };
    /** DocumentText */
    DocumentText: {
      /** Doc Id */
      doc_id: string;
      /** Text */
      text: string;
    };
    /** Envelope[BudgetReport] */
    Envelope_BudgetReport_: {
      data?: components['schemas']['BudgetReport'] | null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Envelope[Health] */
    Envelope_Health_: {
      data?: components['schemas']['Health'] | null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Envelope[NoneType] */
    Envelope_NoneType_: {
      /** Data */
      data?: null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Envelope[RunStarted] */
    Envelope_RunStarted_: {
      data?: components['schemas']['RunStarted'] | null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Envelope[RunStatus] */
    Envelope_RunStatus_: {
      data?: components['schemas']['RunStatus'] | null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Envelope[ScenarioDetail] */
    Envelope_ScenarioDetail_: {
      data?: components['schemas']['ScenarioDetail'] | null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Envelope[list[DocumentText]] */
    Envelope_list_DocumentText__: {
      /** Data */
      data?: components['schemas']['DocumentText'][] | null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Envelope[list[RecordingMeta]] */
    Envelope_list_RecordingMeta__: {
      /** Data */
      data?: components['schemas']['RecordingMeta'][] | null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Envelope[list[ScenarioSummary]] */
    Envelope_list_ScenarioSummary__: {
      /** Data */
      data?: components['schemas']['ScenarioSummary'][] | null;
      error?: components['schemas']['ApiError'] | null;
      /** Success */
      success: boolean;
    };
    /** Finding */
    Finding: {
      /** Billed */
      billed?: string | null;
      /** Claim */
      claim?: string | null;
      /** Confidence */
      confidence?: number | null;
      /** Doc Id */
      doc_id: string;
      /**
       * Evidence
       * @default []
       */
      evidence: components['schemas']['SpanRef'][];
      /** Expected */
      expected?: string | null;
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /**
       * Lane
       * @default auto
       * @enum {string}
       */
      lane: 'auto' | 'review';
      /** Line Ref */
      line_ref?: string | null;
      /** Review Reason */
      review_reason?: string | null;
      /** Risk */
      risk?: ('low' | 'medium' | 'high' | 'critical') | null;
      /**
       * Traceable
       * @default true
       */
      traceable: boolean;
      /** Variance */
      variance?: string | null;
      /** Verdict */
      verdict?:
        | (
            | 'present'
            | 'absent'
            | 'partial'
            | 'verified'
            | 'unsupported'
            | 'contradicted'
            | 'fabricated'
          )
        | null;
    };
    /**
     * Health
     * @description Liveness payload for `GET /api/health`.
     */
    Health: {
      /**
       * Status
       * @constant
       */
      status: 'ok';
    };
    /** Metrics */
    Metrics: {
      /** Cost Usd */
      cost_usd: string | null;
      /** Input Tokens */
      input_tokens: number;
      /** Latency Ms */
      latency_ms: number;
      /** Output Tokens */
      output_tokens: number;
      /** Requests */
      requests: number;
    };
    /** ModelNames */
    ModelNames: {
      /** Jev */
      jev: string;
      /** Llm */
      llm: string;
    };
    /**
     * Provenance
     * @description Where answers came from. Replays are always labelled as recorded.
     */
    Provenance: {
      /**
       * Kind
       * @enum {string}
       */
      kind: 'live' | 'recorded';
      /** Models */
      models: string[];
      /** Recorded At */
      recorded_at?: string | null;
      /** Recording Id */
      recording_id?: string | null;
    };
    /** RecordingMeta */
    RecordingMeta: {
      /** Id */
      id: string;
      /** Jev Model */
      jev_model: string;
      /** Llm Model */
      llm_model: string;
      /** Recorded At */
      recorded_at: string;
      /** Scenario Id */
      scenario_id: string;
    };
    /** RunRequest */
    RunRequest: {
      /**
       * Mode
       * @enum {string}
       */
      mode: 'live' | 'replay';
      /**
       * Pace
       * @default true
       */
      pace: boolean;
      /** Recording Id */
      recording_id?: string | null;
      /** Scenario Id */
      scenario_id: string;
    };
    /** RunResult */
    RunResult: {
      /**
       * Mode
       * @enum {string}
       */
      mode: 'live' | 'replay';
      /** Recording Id */
      recording_id?: string | null;
      /** Run Id */
      run_id: string;
      /** Scenario Id */
      scenario_id: string;
      /** Sides */
      sides: {
        [key: string]: components['schemas']['SideResult'];
      };
    };
    /** RunStarted */
    RunStarted: {
      /** Run Id */
      run_id: string;
    };
    /** RunStatus */
    RunStatus: {
      error: components['schemas']['ApiError'] | null;
      /**
       * Mode
       * @enum {string}
       */
      mode: 'live' | 'replay';
      result: components['schemas']['RunResult'] | null;
      /** Run Id */
      run_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'running' | 'completed' | 'failed';
    };
    /** ScenarioDetail */
    ScenarioDetail: {
      /** Description */
      description: string;
      /** Id */
      id: string;
      /** Live Enabled */
      live_enabled: boolean;
      /** Llm Prompt */
      llm_prompt: string;
      models: components['schemas']['ModelNames'];
      /** Title */
      title: string;
    };
    /** ScenarioSummary */
    ScenarioSummary: {
      /** Description */
      description: string;
      /** Id */
      id: string;
      /** Title */
      title: string;
    };
    /** ScoreItem */
    ScoreItem: {
      /** Finding Id */
      finding_id: string | null;
      /** Key Id */
      key_id: string;
      /** Label */
      label?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'correct' | 'correct_in_review' | 'wrong_value' | 'missed';
    };
    /** Scorecard */
    Scorecard: {
      /** Correct */
      readonly correct: number;
      /** Correct In Review */
      readonly correct_in_review: number;
      /** False Positives */
      false_positives: string[];
      /** Items */
      items: components['schemas']['ScoreItem'][];
      /** Of */
      readonly of: number;
      /** Summary */
      summary: components['schemas']['SummaryRow'][];
      /** Trap Hits */
      trap_hits: string[];
      variance?: components['schemas']['VarianceTotal'] | null;
    };
    /** SideResult */
    SideResult: {
      /** Findings */
      findings: components['schemas']['Finding'][];
      metrics: components['schemas']['Metrics'];
      /**
       * Notes
       * @default []
       */
      notes: string[];
      provenance: components['schemas']['Provenance'];
      scorecard: components['schemas']['Scorecard'];
      /**
       * Side
       * @enum {string}
       */
      side: 'jev' | 'llm';
    };
    /**
     * SpanRef
     * @description Where a value or quote came from: document id plus character offsets.
     */
    SpanRef: {
      /** Doc Id */
      doc_id: string;
      /** End */
      end: number;
      /** Start */
      start: number;
      /** Text */
      text: string;
    };
    /**
     * SummaryRow
     * @description A scenario-specific results row. The UI formats `value` by `kind` and shows `note`
     *     after it; it never computes anything from it. Both sides of a run must use the same
     *     labels: the UI lines their rows up by label, in the first side's order.
     */
    SummaryRow: {
      /**
       * Kind
       * @enum {string}
       */
      kind: 'count' | 'money' | 'text';
      /** Label */
      label: string;
      /** Note */
      note?: string | null;
      /** Ok */
      ok?: boolean | null;
      /** Value */
      value: string | null;
    };
    /**
     * VarianceTotal
     * @description S1's total variance against the answer key's.
     */
    VarianceTotal: {
      /** Exact */
      readonly exact: boolean;
      /** Expected */
      expected: string;
      /** Reported */
      reported: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  budget_api_budget_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_BudgetReport_'];
        };
      };
      /** @description Failure envelope */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_Health_'];
        };
      };
    };
  };
  start_run_api_runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RunRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_RunStarted_'];
        };
      };
      /** @description Failure envelope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
    };
  };
  get_run_api_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_RunStatus_'];
        };
      };
      /** @description Failure envelope */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
    };
  };
  events_api_runs__run_id__events_get: {
    parameters: {
      query?: never;
      header?: {
        'last-event-id'?: number | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-sent events: `id` is the event seq, `event` its type (run_started, step, finding, side_completed, run_completed, run_failed), `data` the RunEvent JSON. Send Last-Event-ID to resume. The stream closes after run_completed or run_failed; clients should close too. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': unknown;
        };
      };
      /** @description Run finished and every event was already seen */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Failure envelope */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
    };
  };
  list_scenarios_api_scenarios_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_ScenarioSummary__'];
        };
      };
    };
  };
  scenario_api_scenarios__scenario_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_ScenarioDetail_'];
        };
      };
      /** @description Failure envelope */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
    };
  };
  documents_api_scenarios__scenario_id__documents_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_DocumentText__'];
        };
      };
      /** @description Failure envelope */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
    };
  };
  recordings_api_scenarios__scenario_id__recordings_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_list_RecordingMeta__'];
        };
      };
      /** @description Failure envelope */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
      /** @description Failure envelope */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Envelope_NoneType_'];
        };
      };
    };
  };
}
